apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: padloc-prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: ./charts/padloc
    repoURL: https://github.com/alexaladov-codefresh/gitops_deployments.git
    targetRevision: padloc-helm
    helm:
      parameters:
        - name: ingress.enabled
          value: 'true'
        - name: ingress.host
          value: 'padloc-prod-alexaladov.support.cf-cd.com'
        - name: dataVolume.storageClassName
          value: 'ebs'
        - name: attachmentsVolume.storageClassName
          value: 'ebs'
        - name: pwa.image
          value: alexaladovcodefresh/padloc-pwa:main-1e5f3b5
        - name: server.image
          value: alexaladovcodefresh/padloc-server:main-1e5f3b5
  destination:
    name: in-cluster
    namespace: padloc
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
